---
- name: Dodanie klucza GPG repozytorium Dockera
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
    gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
  args:
    creates: /etc/apt/trusted.gpg.d/docker.gpg

- name: Dodanie oficjalnego repozytorium Dockera
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present

- name: Instalacja Dockera i Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - python3-docker
    state: present
    update_cache: true

- name: Dodanie uzytkownika group8 do grupy docker
  ansible.builtin.user:
    name: group8
    groups: docker
    append: true

