# 1. Uzupelnij wartosci, a nastepnie zapisz jako ansible/secrets.yml.
# 2. Zaszyfruj plik komenda: ansible-vault encrypt ansible/secrets.yml

pg_monitor_password: "CHANGE_ME_TO_STRONG_PASSWORD" # Haslo konta monitorujacego tworzonego w roli mariadb.
zabbix_api_password: "CHANGE_ME_TO_ZABBIX_API_PASSWORD" # Haslo konta API Zabbix (np. dla użytkownika Admin).

